from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Optional
from models.graph import GraphNode, GraphEdge, GraphStats, EdgeType, NodeType, ProvenanceTag


class BaseGraphStore(ABC):
    @abstractmethod
    def clear(self) -> None: ...
    @abstractmethod
    def add_node(self, node: GraphNode) -> None: ...
    @abstractmethod
    def add_edge(self, edge: GraphEdge) -> None: ...
    @abstractmethod
    def get_node(self, node_id: str) -> Optional[GraphNode]: ...
    @abstractmethod
    def get_all_nodes(self, types: Optional[list[NodeType]] = None, language: Optional[str] = None) -> list[GraphNode]: ...
    @abstractmethod
    def get_all_edges(self, types: Optional[list[EdgeType]] = None, min_confidence: float = 0.0, include_provenances: Optional[list[ProvenanceTag]] = None) -> list[GraphEdge]: ...
    @abstractmethod
    def get_edges_from(self, node_id: str, edge_types: Optional[list[EdgeType]] = None) -> list[GraphEdge]: ...
    @abstractmethod
    def get_edges_to(self, node_id: str, edge_types: Optional[list[EdgeType]] = None) -> list[GraphEdge]: ...
    @abstractmethod
    def get_stats(self) -> GraphStats: ...
    @abstractmethod
    def find_nodes_by_name(self, name: str, limit: int = 20) -> list[GraphNode]: ...
    @abstractmethod
    def shortest_path(self, from_id: str, to_id: str) -> list[str]: ...
    @abstractmethod
    def get_file_fingerprint(self, file_path: str) -> Optional[str]: ...
    @abstractmethod
    def set_file_fingerprint(self, file_path: str, fingerprint: str) -> None: ...
    @abstractmethod
    def get_tracked_files(self) -> dict[str, str]: ...
    @abstractmethod
    def remove_file_records(self, file_path: str) -> None: ...
    @abstractmethod
    def get_related_files(self, file_path: str) -> set[str]: ...
    @abstractmethod
    def clear_model_inferences(self) -> None: ...

    def upsert_node(self, node: GraphNode) -> None:
        self.add_node(node)

    def upsert_edge(self, edge: GraphEdge) -> None:
        self.add_edge(edge)
